repos:
    - repo: https://github.com/psf/black
      rev: 21.5b0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
        - id: check-added-large-files
        - id: double-quote-string-fixer
        - id: end-of-file-fixer
        - id: no-commit-to-branch
          args: [--branch, master]
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: 'v1.5.7'
      hooks:
        - id: autopep8
